### ISSUE TITLE
using password to make API calls is deprecated

### ISSUE THREAD

**Issue by kzidane** [cs50/lib50#41]
https://github.com/cs50/lib50/blob/develop/lib50/_api.py#L956

**Comment by pazz** [comment]
Hey! I've recently received a deprecation info by email from github.
Could you elaborate why this issue is closed? Is this not a problem?
I'm wondering about calling check50 from within a lab environment, which is not cached afaik, so it would be tricky to ask students to use API tokens instead of user/passwd..

**Comment by pazz** [comment]
Just FTR, this is the email I received.
The linked document says that user/passwd authentification will stop working on *November 13, 2020*
and I believe that this means check50 and submit50 will effectively stop working from the online labs/IDE environments.
If you are working on a work-around, but also otherwise and everything breaks soon, please let me know so that I (and many others) can plan ahead. Thanks!
 
```
Hi @pazz,

On August 3rd, 2020 at 15:54 (UTC) you used a password to access an endpoint through the GitHub API using
python-requests/2.22.0:

https://api.github.com/user

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit
https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested
workarounds and removal dates.

Thanks,
The GitHub Team
```
